### ISSUE TITLE
Is data from kaggle different from here?

### ISSUE THREAD

**Issue by kxhit** [cvdfoundation/google-landmark#17]
Hi! I find another source of data from kaggle https://www.kaggle.com/c/landmark-retrieval-2020/data
What's the relation betweeen kaggle data/csv with data/csv in this repo? I'm confused. Thanks if you could give some explanation.

**Comment by Moon1019** [comment]
In my opinion, Kaggle basically allows you to find and publish datasets and also the csv, it can be imported or exported using programs that stores data in tables.

**Comment by andrefaraujo** [comment]
The one listed in this repo is the 100% official/complete version.

In Kaggle, in some cases the data may have been subsampled/resized, depending on the setting. (for example, in the pointer you gave, it shows the GLDv2-clean version of the training set -- `The training data for this competition comes from a cleaned version of the Google Landmarks Dataset v2 (GLDv2)`)
