### ISSUE TITLE
duplicate file across each download batch

### ISSUE THREAD

**Issue by cairenke** [cvdfoundation/google-landmark#2]
Hi, thanks for sharing this! Below is the log displayed when I tried to run this script. But it seems for each batch, one file that belongs to the previous batch will be re-downloaded. Any idea what's happening about this duplicate?

Downloading images_000.tar...
Downloading images_001.tar...
Downloading images_002.tar...
Downloading images_003.tar...
Downloading images_004.tar...
Downloading images_005.tar...
**Downloading images_006.tar...**
images_004.tar extracted!
images_000.tar extracted!
images_002.tar extracted!
images_001.tar extracted!
**images_006.tar extracted!**
images_003.tar extracted!
images_005.tar extracted!
**Downloading images_006.tar...**
Downloading images_007.tar...
Downloading images_008.tar...
Downloading images_009.tar...
Downloading images_010.tar...
Downloading images_011.tar...
Downloading images_012.tar...
images_012.tar extracted!
images_011.tar extracted!
images_008.tar extracted!
images_009.tar extracted!
**images_006.tar extracted!**
images_007.tar extracted!
images_010.tar extracted!

**Comment by dbishai** [comment]
Hmm, did you run the script twice by accident? Did you make any modifications to the script?

**Comment by cairenke** [comment]
Thanks for your reply. No I didn't make any changes and just ran it once on
a Google cloud vm. For each download batch, one file is duplicate, i.e.
1,2,3,4,5,6;  6,7,8,9,10,11,12;  12,13,14,15,16,17,18

**Comment by dbishai** [comment]
Oh I see, I misunderstood. I'll issue a PR to fix this. Thanks for reporting!
