### ISSUE TITLE
Sort landmarks based on country

### ISSUE THREAD

**Issue by StanislavHinov** [cvdfoundation/google-landmark#20]
Hello @andrefaraujo , is there a way that i can get landmarks that are only in one country from the dataset?

I can see in the visualization here - https://storage.googleapis.com/gld-v2/web/index.html that i can select a country and i get a list of the landmarks in it, is there a variable for the country in which the landmark is located in?

Or is there a way to get a list of the landmarks in a certain country, in my case Bulgaria, that are in the dataset.  

Thank  you in advance!:  )

**Comment by andrefaraujo** [comment]
Sorry for the delayed response!

Yes, there is a way. Using the country's 2-letter code (eg, for Bulgaria it would be `BG`), you can find a json file listing the landmarks using the following URL: https://storage.googleapis.com/gld-v2/data/train/country/BG.json (for other countries, please replace `BG` by their desired 2-letter country code).

Also, a list of all country codes which can be used can be found here: https://storage.googleapis.com/gld-v2/data/train/country_codes.json
