### ISSUE TITLE
geo-location labels

### ISSUE THREAD

**Issue by liecn** [cvdfoundation/google-landmark#26]
Hi @andrefaraujo,
I am working on a research project with the GLD v2, which requires the geo-location of each image, such as the lat and lon. For example, I want to plot the figure in the paper. 
![image](https://user-images.githubusercontent.com/32219716/167213824-b8e2cbba-1c27-49a7-92b0-b4f22b755e50.png)

Could you please provide me the geo-location label for each image or tell me where I can get this information for plotting such a figure. Thank you so much!

Best,
Chenning

**Comment by andrefaraujo** [comment]
Hmmm, if I remember correctly the training images may have EXIF information which would give their location? Did you try this?

**Comment by liecn** [comment]
Thanks so much for your reply. I try to read the EXIF information but cannot find the location. Attached please find the result from an online viewer (https://exifdata.com/exif.php).

Best,
Chenning

[cid:27042333-1A0B-4D35-8D6F-3ADD738463EE]

On May 9, 2022, at 11:12 AM, André Araujo ***@***.******@***.***>> wrote:



Hmmm, if I remember correctly the training images may have EXIF information which would give their location? Did you try this?

**Comment by liecn** [comment]
hi @andrefaraujo ,

I figured out something. It provides the table from landmark_id to the category, whose URL can be used to get the landmark's location via the Wikimedia commons API.

I wonder if you have the mapping table from the landmark to its geo-location or any processing scripts with respect to the Wikimedia commons API.

I really appreciate your time!

**Comment by andrefaraujo** [comment]
Thanks! Great to hear you found this mapping to landmark location which is helpful to you.

We unfortunately don't have a mapping from landmark to its geo-location, or processing scripts you mentioned.

Closing this issue since I think it's dealt with, but please feel free to reopen as needed.

**Comment by zisismp4** [comment]
> hi @andrefaraujo ,
> 
> I figured out something. It provides the table from landmark_id to the category, whose URL can be used to get the landmark's location via the Wikimedia commons API.
> 
> I wonder if you have the mapping table from the landmark to its geo-location or any processing scripts with respect to the Wikimedia commons API.
> 
> I really appreciate your time!

@liecn Did you find any easy way to extract the location info from wikimedia commons ?

**Comment by liecn** [comment]
Hi @zisismp4,

I do get the location table by webscraping, although it has None values for several landmarks. I will upload them today or tomorrow. I need some time for wrapping up.

**Comment by zisismp4** [comment]
@liecn that sounds great! I look forward to your results.
How did you manage to make so many requests without having trouble ?

**Comment by liecn** [comment]
[train_label_to_category_loc.csv](https://github.com/cvdfoundation/google-landmark/files/8782039/train_label_to_category_loc.csv)
Hi @zisismp4 @andrefaraujo , I attached the sheet with the loc (i.e., lat, lon), following the train_label_to_category.csv. Feel free to use it.

attached please also find the script. No optimization for this so it can be a little slow.

```
# import requests module
import requests
import json
import html_to_json
import re,os
import csv

abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)

coor_pattern="[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)"
key_list=["html","head","script"]
# Making a get request
target_idx=11
with open('train_label_to_category.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',', quotechar='"')
    with open('train_label_to_category_loc_'+str(target_idx)+'.csv', 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['landmark_id', 'category', 'lon','lat'])
        for idx,row in enumerate(spamreader):
            if (target_idx-1)*20000<idx<=target_idx*20000:
                url=row[1]
                response = requests.get(url)
                json_ = html_to_json.convert(response.text)
                for key in key_list:
                    json_=json_[key][0]
                json_=json_["_value"]
                # with open("debug.json", "w") as debug_file:
                #     json.dump(json_, debug_file, indent=4, sort_keys=True)
                re_obj=re.search(coor_pattern,json_)
                if re_obj:
                    row.extend(re_obj.group(0).replace("\n", "").split(","))
                else:
                    row.extend(['None','None'])
                    print("errorr in finding loc for", row[0])
                writer.writerow(row)
```
