### ISSUE TITLE
3 computed checksum did NOT match in train

### ISSUE THREAD

**Issue by goodhope258** [cvdfoundation/google-landmark#8]
cd train

images_172.tar: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
images_206.tar: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
images_225.tar: FAILED
md5sum: WARNING: 1 computed checksum did NOT match

**Comment by ahmadmobeen** [comment]
re-download the files. I had same problem for different files. But re-downloading checksum matched.
