### ISSUE TITLE
Missing Important Landmarks

### ISSUE THREAD

**Issue by FadyMorris** [cvdfoundation/google-landmark#9]
There is no entry in the dataset for "Leaning Tower of Pisa" and "Christ the Redeemer" statue

**Comment by andrefaraujo** [comment]
That's true! We rely on labels collected from Wikimedia Commons, and sometimes the categories are not so well-defined. For the train and index sets, we enforce the restriction that each image must be assigned to a single category; this ends up eliminating many photos, which could be tagged with multiple categories.
